#cloud-config
timezone: 'Asia/Singapore'
resize_rootfs: true
apt:
  sources:
    cmaker.list:
      source: deb [arch=${arch}] https://ppa.launchpadcontent.net/george-edison55/cmake-3.x/ubuntu $RELEASE main
      keyid: 1024R/B118CD3C377DF930EDD06C67084ECFC5828AB726
users:
- default
- name: yugabyte
  gecos: YugabyteDB Developer
  groups:
  - users
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
  - ${public-key}
write_files:
- path: /etc/netplan/99-lo.yaml
  defer: true
  owner: root:root
  permissions: '0611'
  content:  |
    network:
      ethernets:
        lo:
          addresses:
          - 127.0.0.1/8
          - 127.0.0.2/8
          - 127.0.0.3/8
          - 127.0.0.4/8
          - 127.0.0.5/8
          - 127.0.0.6/8
          - 127.0.0.7/8
          - 127.0.0.8/8
          - 127.0.0.9/8
          - 127.0.0.10/8
          - 127.0.0.11/8
          - 127.0.0.12/8
          - 127.0.0.13/8
          - 127.0.0.14/8
          - 127.0.0.15/8
      version: 2
packages:
- apt-transport-https
- autoconf
- build-essential
- ca-certificates
- containerd.io
- cmake
- curl
- file
- gettext
- git
- golang-1.18
- libffi-dev
- locales
- maven
- ninja-build
- npm
- patchelf
- pkg-config
- python-is-python3
- python3
- python3-dev
- python3-venv
- rsync
- software-properties-common
- unattended-upgrades
%{ if length(write-files) > 0 ~}
write_files:
%{ endif ~}
%{ for file in write-files ~}
- path: ${file.path}
  defer: ${file.defer}
  append: ${file.append}
  permissions: "${file.permissions}"
  owner: "${file.owner}"
%{ if file.encoding != "" ~}
  encoding: "${file.encoding}"
%{ endif ~}
%{ if file.binary ~}
  content: !!binary |
    ${indent(4, file.content)}
%{ else ~}
  content: |
    ${indent(4, file.content)}
%{ endif ~}
%{ endfor ~}

%{ if length(boot-commands) > 0 ~}
bootcmd:
%{ endif ~}
%{ for b in boot-commands ~}
- |
  ${b}
%{ endfor ~}
runcmd:
- locale-gen en_US.UTF-8
%{ for s in startup-commands ~}
- |
  ${s}
%{ endfor ~}
