#cloud-config
timezone: 'Asia/Singapore'
resize_rootfs: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
groups:
  - docker

users:
- default
- name: yugabyte
  gecos: YugabyteDB Admin
  groups:
  - users
  - docker
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true
system_info:
  default_user:
    groups: [docker]
write_files:
- path: /etc/netplan/99-lo.yaml
  defer: true
  owner: root:root
  permissions: '0611'
  content:  |
    network:
      ethernets:
        lo:
          addresses:
          - 127.0.0.1/8
          - 127.0.0.2/8
          - 127.0.0.3/8
          - 127.0.0.4/8
          - 127.0.0.5/8
          - 127.0.0.6/8
          - 127.0.0.7/8
          - 127.0.0.8/8
          - 127.0.0.9/8
          - 127.0.0.10/8
          - 127.0.0.11/8
          - 127.0.0.12/8
          - 127.0.0.13/8
          - 127.0.0.14/8
          - 127.0.0.15/8
      version: 2
- path: /root/.config/code-server/config.yaml
  defer: true
  owner: root:root
  permission: '0611'
  content: |
    bind-addr: 0.0.0.0:443
    auth: password
    password: ${password}
    cert: /root/certs/server-cert.pem
    cert-key: /root/certs/server-key.pem
- path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
  content: |
    net.ipv4.conf.all.forwarding=1
packages:
- unattended-upgrades
- apt-transport-https
- ca-certificates
- containerd.io
- curl
- direnv
- git
- golang-go
- docker-ce
- docker-ce-cli
- gnupg
- gnupg-agent
- jq
- net-tools
- openjdk-17-jdk
- software-properties-common
- docker-compose
- python-is-python3
bootcmd:
- gsutil cp -R ${asset-bucket-location}/certs/* /root/certs/
runcmd:
- mkdir /root/certs
- gsutil cp -R ${asset-bucket-location}/certs/* /root/certs/
- curl -fsSL https://code-server.dev/install.sh | HOME=/root bash
- systemctl enable --now code-server@root
- wget https://s3.us-west-2.amazonaws.com/downloads.yugabyte.com/repos/reporpms/yb-apt-repo_1.0.0_all.deb
- apt-get install ./yb-apt-repo_1.0.0_all.deb
- apt-get update -qqy
- apt-get install -qqy yb-voyager
- curl -sSL https://downloads.yugabyte.com/releases/2.18.0.1/yugabyte-2.18.0.1-b4-linux-x86_64.tar.gz -o /root/yugabyte.tgz
- mkdir -p /root/yugabyte mkdir /root/bin
- tar -C /root/yugabyte --owner=yugabyte --group=yugabyte -xzf /root/yugabyte.tgz --strip-components=1
- cd /root/yugabyte
- ./bin/post_install.sh
- curl -sSL https://raw.githubusercontent.com/yugabyte/yugabyte-db/master/bin/yb-docker-ctl -o /root/bin/yb-docker-ctl && chmod +x /root/bin/yb-docker-ctl
- echo "export PATH=\$PATH:/root/bin:/root/yugabyte/bin:/root/yugabyte/tools:/root/yugabyte/posgres/bin" >> /root/.bashrc
- netplan apply
