#cloud-config
timezone: 'Asia/Singapore'
resize_rootfs: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    kubernetes.list:
      source: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
      keyid: A362B822F6DEDC652817EA46B53DC80D13EDEF05
groups:
  - docker

ssh_authorized_keys:
- ${public-key}

users:
- default
system_info:
  default_user:
    groups: [docker]
write_files:
- path: /root/.tmux.conf
  defer: true
  owner: root:root
  permission: '0611'
  content: |
    # Dracula Colours
    # background_color '#282a36'
    # current_line_color '#44475a'
    # foreground_color '#f8f8f2'
    # comment_color '#6272a4'
    # cyan '#8be9fd'
    # green '#50fa7b'
    # orange '#ffb86c'
    # pink '#ff79c6'
    # purple '#bd93f9'
    # red '#ff5555'
    # yellow '#f1fa8c'


    # terminal colors
    set -g default-terminal "xterm-256color"

    # pane border
    set -g pane-border-style fg='#6272a4'
    set -g pane-active-border-style fg='#ff79c6'

    # message text
    set -g message-style bg='#44475a',fg='#8be9fd'

    set -g status-style bg='#44475a',fg='#bd93f9'
    set -g status-interval 1

    # status left
    # are we controlling tmux or the content of the panes?
    set -g status-left '#[bg=#f8f8f2]#[fg=#282a36]#{?client_prefix,#[bg=#ff79c6],} ☺ '

    # are we zoomed into a pane?
    set -ga status-left '#[bg=#44475a]#[fg=#ff79c6] #{?window_zoomed_flag, ↕  ,   }'


    # window status
    set-window-option -g window-status-style fg='#bd93f9',bg=default
    set-window-option -g window-status-current-style fg='#ff79c6',bg='#282a36'

    # status right
    set -g status-right '#[fg=#8be9fd,bg=#44475a]#[fg=#44475a,bg=#8be9fd] #(tmux-mem-cpu-load -g 5 --interval 2) '
    set -ga status-right '#[fg=#ff79c6,bg=#8be9fd]#[fg=#44475a,bg=#ff79c6] #(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") '
    set -ga status-right '#[fg=#bd93f9,bg=#ff79c6]#[fg=#f8f8f2,bg=#bd93f9] %a %H:%M:%S #[fg=#6272a4]%Y-%m-%d '


    set-option -g status-keys vi
    set-option -g mode-keys vi
    set -g mouse on

    #no command delay
    set -sg escape-time 0

    #using C-a as prefix
    unbind C-b
    set-option -g prefix C-Space
    bind C-Space send-prefix

    set -g base-index 1
    setw -g pane-base-index 1

    bind C-c new-window
    bind A command-prompt 'rename-window %%'
    bind C-a last-window

    bind '|' split-window -h -c "#{pane_current_path}"
    bind '\' split-window -fh -c "#{pane_current_path}"
    bind - split-window -v -c "#{pane_current_path}"
    bind _ split-window -v -c "#{pane_current_path}"

    bind c new-window -c "#{pane_current_path}"

    bind r source-file ~/.tmux.conf \; display "Reloaded!"


    set -g @continuum-restore 'on'

    # List of plugins
    set -g @plugin 'tmux-plugins/tpm'
    set -g @plugin 'tmux-plugins/tmux-sensible'
    set -g @plugin 'tmux-plugins/tmux-resurrect'
    set -g @plugin 'tmux-plugins/tmux-continuum'

    # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
    run '~/.tmux/plugins/tpm/tpm'

%{ for file in write-files ~}
- path: ${file.path}
  defer: ${file.defer}
  append: ${file.append}
  permissions: "${file.permissions}"
  owner: "${file.owner}"
%{ if file.encoding != "" ~}
  encoding: "${file.encoding}"
%{ endif ~}
%{ if file.binary ~}
  content: !!binary |
    ${indent(4, file.content)}
%{ else ~}
  content: |
    ${indent(4, file.content)}
%{ endif ~}
%{ endfor ~}
packages:
- apt-transport-https
- kubectl
- ca-certificates
- containerd.io
- curl
- direnv
- docker-ce
- docker-ce-cli
- docker-compose
- fzf
- git
- gnupg
- gnupg-agent
- jq
- neovim
- net-tools
- python-is-python3
- software-properties-common
- tmux
- unzip
- unattended-upgrades
runcmd:
- curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -oqq awscliv2.zip -d /tmp && rm awscliv2.zip && /tmp/aws/install --update && rm -rf /tmp/aws && aws --version
- curl -sSL https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz | tar -C /usr/local/bin -xzvf- k9s
- curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
- git clone https://github.com/tmux-plugins/tpm /root/.tmux/plugins/tpm
- cp -r --no-preserv=ownership .tmux /home/ubuntu/
- install -o ubuntu -g ubuntu -m 0600 /root/.tmux.conf /home/ubuntu/.tmux.conf
- curl -sS https://starship.rs/install.sh | sh -s -- -f
- echo "eval \"\$(starship init bash)\"" >> /root/.bashrc
- echo "source /usr/share/doc/fzf/examples/key-bindings.bash" >> /root/.bashrc
- echo "eval \"\$(direnv hook bash)\"" >> /root/.bashrc
- echo "complete -C '/usr/local/bin/aws_completer' aws"  >>/root/.bashrc
- echo "eval \"\$(starship init bash)\"" >> /home/ubuntu/.bashrc
- echo "source /usr/share/doc/fzf/examples/key-bindings.bash" >>/home/ubuntu/.bashrc
- echo "eval \"\$(direnv hook bash)\"" >>/home/ubuntu/.bashrc
- echo "complete -C '/usr/local/bin/aws_completer' aws"  >>/home/ubuntu/.bashrc
