#cloud-config
timezone: 'Asia/Singapore'
resize_rootfs: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
groups:
  - docker

users:
- default
- name: yugabyte
  gecos: YugabyteDB Admin
  groups:
  - users
  - docker
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNFVe3z8zrNMJLyRXRMOGDuyJryW8kzbR9vsZ3QlPMrJmjEQvqL3c21VJAbJG/0BwpQbUsR/YNdww61w+7+bRiXCCI70jsBEt0KZqSYNmSNmiRjJdQwP+g7Kiav8E/Kb01pSVyDD3CfNYBzMPksxwn0F/9dHlD8d1JMjbxQ8Pc1jYt3ShFWLcvLAxfFXfAPFXnwo++b9JAjtzlDh7ykc5RbErQZmh2ZUS7FRbN8J/CoksH0fJOyLYrn4+CDtJlI5EgSEnSDbbF4L4vJVfCL20+1Q3r0Bfez5BcLj+I69goB/Ij8iHh3X3KfihjWppWw42Vs6w7SbEjmkn50/D/fPzHmv8Cdy4vFQLPWr4ybREmyvnY0NeIJJ0BYlb48JkI6wPlHPz46QrnFUh6gWRIzzdf611jlz4LOLMlZWeIiwXCXL0ejKbNKtQuS6xX5RTjrlTXxgmS1O4LYAM/NmX80PNL2cuaHoG8PLlAHGQthYcUIhfW3M3WUwHYi+VsJsXRZhU= yba-apj-demo-shr
system_info:
  default_user:
    groups: [docker]
write_files:
- path: /etc/netplan/99-lo.yaml
  defer: true
  owner: root:root
  permissions: '0611'
  content:  |
    network:
      ethernets:
        lo:
          addresses:
          - 127.0.0.1/8
          - 127.0.0.2/8
          - 127.0.0.3/8
          - 127.0.0.4/8
          - 127.0.0.5/8
          - 127.0.0.6/8
          - 127.0.0.7/8
          - 127.0.0.8/8
          - 127.0.0.9/8
          - 127.0.0.10/8
          - 127.0.0.11/8
          - 127.0.0.12/8
          - 127.0.0.13/8
          - 127.0.0.14/8
          - 127.0.0.15/8
      version: 2
- path: /root/.tmux.conf
  defer: true
  owner: root:root
  permission: '0611'
  content: |
    set -g @plugin 'tmux-plugins/tpm'
    set -g @plugin 'tmux-plugins/tmux-sensible'

    run '~/.tmux/plugins/tpm/tpm'
- path: /root/.config/code-server/config.yaml
  defer: true
  owner: root:root
  permission: '0611'
  content: |
    bind-addr: 0.0.0.0:443
    auth: password
    password: ${password}
    cert: /root/certs/server-cert.pem
    cert-key: /root/certs/server-key.pem
    app-name: YugabyteDB Demo
    welcome-text: |
      Welcome to YugabyteDB Demo Environment.
      Test
      Test
      Test
- path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
  content: |
    net.ipv4.conf.all.forwarding=1
packages:
- unattended-upgrades
- apt-transport-https
- ca-certificates
- containerd.io
- curl
- docker-ce
- docker-ce-cli
- software-properties-common
- docker-compose
- python-is-python3
bootcmd:
%{ for s in startup-commands ~}
- |
  ${s}
%{ endfor ~}
- ${startup-command}
runcmd:
- mkdir /root/certs
- openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /root/certs/server-key.pem -out /root/certs/server-cert.pem -subj /C=SG/ST=SG/L=SG/O=yugabytedb/CN=demo
- curl -sSL https://raw.githubusercontent.com/yugabyte/yugabyte-db/master/bin/yb-docker-ctl -o /root/bin/yb-docker-ctl && chmod +x /root/bin/yb-docker-ctl
%{ for s in startup-commands ~}
- |
  ${s}
%{ endfor ~}
