#cloud-config
timezone: 'Asia/Singapore'

users:
- default
- name: yugabyte
  gecos: YugabyteDB Admin
  groups: users
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  local_passwd: true
  ssh_authorized_keys:
  - "${pubKey}"

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

write_files:
- path: /etc/replicated.conf
  permissions: "0644"
  content: |+
    ${indent(4,replicatedConf)}
  defer: true
- path: /etc/yugaware.conf
  permissions: "0644"
  content: |+
    ${indent(4,yugawareConf)}
  defer: true
- path: /etc/yugaware.rli
  permissions: "0644"
  content: !!binary |
    ${indent(4,yugawareLicense)}
  defer: true
- path: /usr/local/bin/install-yugaware.sh
  permissions: "0755"
  content: |+
    ${indent(4, installYugaware)}
  defer: true
- path: /usr/local/bin/setup-yugaware.py
  permissions: "0755"
  content: |+
    ${indent(4, setupYugaware)}
  defer: true
- path: /etc/server.cer
  permission: "0655"
  content: |+
    ${indent(4, serverCert)}
  defer: true
- path: /etc/server.key
  permission: "0655"
  content: |+
    ${indent(4, serverKey)}
  defer: true
runcmd:
- if [[ -d /usr/share/pki/ca-trust-source/anchors/ ]]; then  cp /etc/server.cer /usr/share/pki/ca-trust-source/anchors/ ;  update-ca-trust ; fi
- if [[ -d /usr/local/share/ca-certificates/ ]]; then cp /etc/server.cer /usr/local/share/ca-certificates/server.cer; update-ca-certificates ; fi
- export CLOUD_CONFIG_JSON='${cloudConfigJson}'
- export STAGING_BUCKET='${stagingBucket}'
- export ONLINE_INSTALL=${onlineInstall}
- /usr/local/bin/install-yugaware.sh
- /usr/local/bin/setup-yugaware.py
